---
# handlers file for web_service
- name: Restart_Apache_RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart_Apache_Ubuntu
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
