---
- name: Provisioning Instances 
  hosts: tomcat 
  become: yes
  vars:
    java: 1.8.0
    extra_repository: epel-release
#    utils_inst: mc
 
  roles:
    - base
    - web-service     
    - java

