---
- name: Provisioning Instances 
  hosts: jfrog 
  become: yes
  vars:
    java: 1.8.0
    extra_repository: epel-release
 
  roles:
    - base
#    - docker  
#    - web-service     
#    - java

