---
- name: My dear playbook
  hosts: all
  become: yes

  vars:
   mytext: "Privet ot Soft-Tronil Lviv"

  tasks:
  - name: Ping test
    ping:

  - name: Create folders
    include: create_folders.yml

  - name: Create files
    include: create_files.yml

