---
- name: My dear playbook
  hosts: all
  become: yes

  vars:
   mytext: "Privet ot Soft-Tronil Lviv"

  tasks:
  - name: Ping test
    ping:

  - name: Create folder tomcat
    file: 
     path: /home/tomcat/folder1
     state: directory
     mode: 0755    

  - name: Create folder jenkins
    file:
     path: /home/jenkins/folder2
     state: directory
     mode: 0755

  - name: Create file1
    copy: 
      dest: /home/tomcat/folder1/file1.txt
      content: |
        Text Line1, in file1      
        Text Line2, {{ mytext }}

  - name: Create file2
    copy:
      dest: /home/jenkins/folder2/file2
      content: |
        Text Line1, in file2      
        Text Line2, {{ mytext }}


