---
- name: Use loop in the provisioning Instances 
  hosts: tomcat,jenkins 
  become: yes

 
 
  tasks:
    - name: Check Linux version
      debug: var="ansible_os_family"

    - name: install epel-release
      yum: name=epel-release state=present


    - name: Install packages for RedHat
      yum: name={{ item }} state=latest
      with_items:
#            - epel-release  
            - mc
            - vim
            - htop
            - bind-utils
            - net-tools


      when: ansible_os_family == "RedHat"

    - name: Install Apache web server for Ubuntu
      apt: name={{ item }} state=latest
      with_items:
            - mc
            - vim
            - htop
            - bind-utils
            - net-tools

      when: ansible_os_family == "Debian"

    

