---

- name: Install packages for RedHat
  yum: name=docker state=latest

- name: Start Docker
  service: name=docker  state=started

# - name: Docker pull an image
#   docker_image:
#     name: jenkis
#     source: pull 

- name: Docker run and expose ports
  shell: docker run -d --name jenkins -p 8080:8080 -p 50000:50000 -v /jenkins_external:/var/jenkins_home jenkins/jenkins:lts-alpine

- name: Setup tools
  shell: |
    CID=$(docker ps -aqf "name=jenkins")
    docker exec -it --user root $CID apk add py3-pip
    docker exec -it --user root $CID pip3 install --upgrade pip
    docker exec -it --user root $CID pip3 install awscli