
- name: install epel-release
  yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"


- name: install mc
  yum: name=mc state=present
  when: ansible_os_family == "RedHat"

- name: install htop
  yum: name=htop state=present
  when: ansible_os_family == "RedHat"


- name: install vim
  yum: name=vim state=present
  when: ansible_os_family == "RedHat"


- name: install bind-utils
  yum: name=bind-utils state=present
  when: ansible_os_family == "RedHat"

- name: install net-tools
  yum: name=net-tools state=present
  when: ansible_os_family == "RedHat"







- name: install mc
  apt: name=mc state=present
  when: ansible_os_family == "Debian"

- name: install htop
  apt: name=htop state=present
  when: ansible_os_family == "Debian"

- name: install vim
  apt: name=vim state=present
  when: ansible_os_family == "Debian"

- name: install dnsutils
  apt: name=dnsutils state=present
  when: ansible_os_family == "Debian"

- name: install net-tools
  apt: name=net-tools state=present
  when: ansible_os_family == "Debian"

